FROM php:8.2-apache

# Install dependencies
RUN apt-get update && apt-get install -y \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    unzip \
    libaio1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

# # Download wait-for-it.sh and make it executable
# RUN curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
#     && chmod +x /usr/local/bin/wait-for-it.sh

# # Make it executable
# RUN chmod +x /usr/local/bin/wait-for-it.sh

# Install Oracle Instant Client (basic and SDK) and OCI8 extension
RUN curl -o instantclient-basic-linux.x64-21.1.0.0.0.zip https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-basic-linux.x64-21.1.0.0.0.zip \
    && curl -o instantclient-sdk-linux.x64-21.1.0.0.0.zip https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-sdk-linux.x64-21.1.0.0.0.zip \
    && unzip instantclient-basic-linux.x64-21.1.0.0.0.zip -d /usr/lib/oracle \
    && unzip instantclient-sdk-linux.x64-21.1.0.0.0.zip -d /usr/lib/oracle \
    && rm instantclient-basic-linux.x64-21.1.0.0.0.zip \
    && rm instantclient-sdk-linux.x64-21.1.0.0.0.zip \
    && echo /usr/lib/oracle/instantclient_21_1 > /etc/ld.so.conf.d/oracle-instantclient.conf \
    && ldconfig \
    && export LD_LIBRARY_PATH=/usr/lib/oracle/instantclient_21_1:$LD_LIBRARY_PATH \
    && echo 'instantclient,/usr/lib/oracle/instantclient_21_1' | pecl install oci8 \
    && docker-php-ext-enable oci8

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
    gd \
    pdo_mysql \
    mysqli \
    zip

# Install PECL extensions
RUN pecl install redis-5.3.7 \
    && pecl install xdebug-3.2.1 \
    && docker-php-ext-enable redis xdebug

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Use the default production configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Configure Apache
RUN a2enmod rewrite

# Set ServerName to suppress the warning
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Set working directory
WORKDIR /var/www/html

# Copy application files
COPY ./php .

# Set permissions
RUN chown -R www-data:www-data /var/www/html